replicaCount: 5



ingress:
  enabled: true
  className: "artemis"
  annotations: 
    artemis.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: artemis-dev.9aws.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: artemis-dev-tls
     hosts:
       - artemis-dev.9aws.com