apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-stage
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/alecz86/argo-demo.git
    path: application
    targetRevision: HEAD
    helm:
      valueFiles: 
      - ../nodejs/envs/stage.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-stage

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true