apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-qa
  namespace: nginx-qa
spec:
  project: default

  source:
    repoURL: https://github.com/alecz86/argo-demo.git
    path: application
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../envs/qa.yaml  # Added space after '-'

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-qa

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
